name: Test Hello action
on: [push]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Run custom action
        uses: ./ # local action
        with:
          who-to-greet: "Wire"
      - name: Show output
        run: echo "Time of greeting ${{ steps.greet.outputs.time }}"
